# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jmarch
tagline:          'A website i'm testing'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme'
url:             
baseurl:          /

author:
  name:           
  url:           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
